version: "3.7"
services:
  jupyter:
    image: jupyter/minimal-notebook
    container_name: jupyter-notebook
    restart: always
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - "work:/home/jovyan/work"
volumes:
  work:
    external:
      name: ${WORK_VOLUME}
