version: "3.3"
services:
  postgres-db:
    image: postgres:10
    container_name: postgres-db
    user: 1000:1000
    restart: always
    env_file: 
      - .env
    ports: 
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
    external: true
volumes:
  pgdata:
    external: true
